name: Build debug kernel
on:
  workflow_dispatch:

jobs:

  build-debug-kernel-a13:
    strategy:
      matrix:
        include:
          - version: "5.10"
            sub_level: 218 
            os_patch_level: 2024-08
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
      debug: true
